client_config_backend: settings
client_config:
  client_id: 86637276718-gq4f9k25tu369rk30j648jfekhe48kf2.apps.googleusercontent.com
  client_secret: WJX1PFwvcvsiHzV40iEeaydA

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install

client_config_file: secrets/client_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: secrets/credentials.json

get_refresh_token: True